name: yeth-bootstrap
plugins:
  - name: vyper
  - name: foundry
  - name: etherscan
ethereum:
  default_network: local
  local:
    default_provider: foundry
  mainnet_fork:
    default_provider: foundry
